inherit_gem:
  rubocop-basic: rubocop.yml

plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1

Metrics/MethodLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
