stack: example

registry:
  server: hub.docker.com
  username:
    - DOCKER_USERNAME
  password:
    - DOCKER_PASSWORD

ssh:
  user: root

environments:
  production:
    hosts:
      - 1.2.3.4
      - 5.6.7.8
  test:
    hosts:
      - 4.3.2.1
      - 8.7.6.5
